### PR TITLE
akit to main

### PR DESCRIPTION
**Pull request by Oliver-Cushman**
for the past month akit has basically been main so lets seal the deal

### CODE REVIEW

**Comment by Jacob1010-h** [comment]
I love these commit messages 😂 they are beautiful ❤️

**Comment by GalexY727** [comment]
someone understood the assignment

**Comment by GalexY727** [comment]
A couple notes before this gets merged, however...
Akit is by no means a tiny change. When I made Jerome command-based in the offseason he *seemed* to work good enough, but I didn't have the same level of quality control when coding him, as it was primarily for a learning experience. Aka, I didn't run that code in any of our off season competitions. If this is to be merged, it means that you're basically locked in for comp to use akit. I recommend you at least make a backup branch of main called `pre-akit` to make sure that you can always fall back during competition if you run into any sort of bugs that you can't explain. If this isn't reviewed by someone else Friday I'll review it :). Well done with the upgrade!

**Comment by Jacob1010-h** [comment]
I 100% agree with Alex here. For something that is this big of a change it should go through multiple reviewers, or at least be able to be easily backed up in case of something terrible. 

I also recommend that all assigned reviewers review the code ASAP. 1. To get familiar with the changes. And 2. To double check multiple times over. At the end of that, then asking for mine or Alex's final review, of which if there is another major change, the process should repeat. 

I know it sounds tedious, but I highly recommend it for something this big and new.

**Comment by Oliver-Cushman** [comment]
> After reading through every single line of code very in depth and completely and absolutely locking in for hours upon hours, I have determine that this is // working

Thank you Zachary Good

**Comment by RudyG252** [comment]
> > After reading through every single line of code very in depth and completely and absolutely locking in for hours upon hours, I have determine that this is // working
> 
> Thank you Zachary Good

Thank you Clint Cushman

**Pull request merged**
